module(...)

-- This file is for use with CoronaSDK™ and was generated by Zwoptex (http://zwoptexapp.com/)
--
-- For more details, see http://developer.anscamobile.com/reference/sprite-sheets

function getSpriteSheetData()

	local sheet = {
		frames = {
		
			{
				name = "0Nothing.png",
				spriteColorRect = { x = 0, y = 0, width = 40, height = 40 }, 
				textureRect = { x = 0, y = 0, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "Afro-Back.png",
				spriteColorRect = { x = 2, y = 2, width = 36, height = 30 }, 
				textureRect = { x = 42, y = 0, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "Afro-Front.png",
				spriteColorRect = { x = 2, y = 2, width = 36, height = 26 }, 
				textureRect = { x = 84, y = 0, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "Afro-Right.png",
				spriteColorRect = { x = 1, y = 2, width = 36, height = 30 }, 
				textureRect = { x = 126, y = 0, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "Arms-Back.png",
				spriteColorRect = { x = 5, y = 27, width = 30, height = 8 }, 
				textureRect = { x = 168, y = 0, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "Arms-Front.png",
				spriteColorRect = { x = 5, y = 28, width = 30, height = 6 }, 
				textureRect = { x = 210, y = 0, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "Arms-Right.png",
				spriteColorRect = { x = 14, y = 31, width = 8, height = 8 }, 
				textureRect = { x = 252, y = 0, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "Balding-Back.png",
				spriteColorRect = { x = 5, y = 18, width = 30, height = 10 }, 
				textureRect = { x = 294, y = 0, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "Balding-Front.png",
				spriteColorRect = { x = 4, y = 17, width = 32, height = 10 }, 
				textureRect = { x = 336, y = 0, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "Balding-Right.png",
				spriteColorRect = { x = 4, y = 15, width = 18, height = 14 }, 
				textureRect = { x = 378, y = 0, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "Beard-Front.png",
				spriteColorRect = { x = 15, y = 26, width = 10, height = 2 }, 
				textureRect = { x = 420, y = 0, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "Beard-Right.png",
				spriteColorRect = { x = 23, y = 25, width = 6, height = 4 }, 
				textureRect = { x = 462, y = 0, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "Blush-Front.png",
				spriteColorRect = { x = 12, y = 24, width = 16, height = 2 }, 
				textureRect = { x = 0, y = 42, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "Blush-Right.png",
				spriteColorRect = { x = 23, y = 23, width = 2, height = 2 }, 
				textureRect = { x = 42, y = 42, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "Bun-Back.png",
				spriteColorRect = { x = 6, y = 6, width = 28, height = 26 }, 
				textureRect = { x = 84, y = 42, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "Bun-Front.png",
				spriteColorRect = { x = 6, y = 6, width = 28, height = 16 }, 
				textureRect = { x = 126, y = 42, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "Bun-Right.png",
				spriteColorRect = { x = 3, y = 6, width = 30, height = 24 }, 
				textureRect = { x = 168, y = 42, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "Earrings-Back.png",
				spriteColorRect = { x = 6, y = 22, width = 28, height = 2 }, 
				textureRect = { x = 210, y = 42, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "Earrings-Front.png",
				spriteColorRect = { x = 6, y = 22, width = 28, height = 2 }, 
				textureRect = { x = 252, y = 42, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "Earrings-Right.png",
				spriteColorRect = { x = 15, y = 23, width = 2, height = 2 }, 
				textureRect = { x = 294, y = 42, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "EyeColor-Front.png",
				spriteColorRect = { x = 15, y = 24, width = 10, height = 2 }, 
				textureRect = { x = 336, y = 42, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "EyeColor-Right.png",
				spriteColorRect = { x = 26, y = 23, width = 2, height = 2 }, 
				textureRect = { x = 378, y = 42, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "EyeLash-Front.png",
				spriteColorRect = { x = 13, y = 22, width = 14, height = 2 }, 
				textureRect = { x = 420, y = 42, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "EyeLash-Right.png",
				spriteColorRect = { x = 24, y = 19, width = 4, height = 2 }, 
				textureRect = { x = 462, y = 42, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "Feet-Back-1.png",
				spriteColorRect = { x = 13, y = 36, width = 14, height = 4 }, 
				textureRect = { x = 0, y = 84, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "Feet-Back-2.png",
				spriteColorRect = { x = 10, y = 36, width = 20, height = 4 }, 
				textureRect = { x = 42, y = 84, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "Feet-Back-3.png",
				spriteColorRect = { x = 12, y = 36, width = 14, height = 4 }, 
				textureRect = { x = 84, y = 84, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "Feet-Front-1.png",
				spriteColorRect = { x = 11, y = 36, width = 16, height = 4 }, 
				textureRect = { x = 126, y = 84, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "Feet-Front-2.png",
				spriteColorRect = { x = 10, y = 36, width = 20, height = 4 }, 
				textureRect = { x = 168, y = 84, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "Feet-Front-3.png",
				spriteColorRect = { x = 12, y = 36, width = 16, height = 4 }, 
				textureRect = { x = 210, y = 84, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "Feet-Right-1.png",
				spriteColorRect = { x = 12, y = 36, width = 16, height = 4 }, 
				textureRect = { x = 252, y = 84, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "Feet-Right-2.png",
				spriteColorRect = { x = 13, y = 36, width = 14, height = 4 }, 
				textureRect = { x = 294, y = 84, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "Feet-Right-3.png",
				spriteColorRect = { x = 12, y = 36, width = 16, height = 4 }, 
				textureRect = { x = 336, y = 84, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "FemaleBody-Back.png",
				spriteColorRect = { x = 10, y = 27, width = 20, height = 8 }, 
				textureRect = { x = 378, y = 84, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "FemaleBody-Front.png",
				spriteColorRect = { x = 9, y = 27, width = 22, height = 8 }, 
				textureRect = { x = 420, y = 84, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "FemaleBody-Right.png",
				spriteColorRect = { x = 12, y = 30, width = 14, height = 8 }, 
				textureRect = { x = 462, y = 84, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "Glasses-Front.png",
				spriteColorRect = { x = 6, y = 19, width = 28, height = 6 }, 
				textureRect = { x = 0, y = 126, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "Glasses-Right.png",
				spriteColorRect = { x = 17, y = 18, width = 14, height = 6 }, 
				textureRect = { x = 42, y = 126, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "HairBand-Front.png",
				spriteColorRect = { x = 7, y = 6, width = 26, height = 6 }, 
				textureRect = { x = 84, y = 126, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "HairBand-Right.png",
				spriteColorRect = { x = 16, y = 5, width = 8, height = 16 }, 
				textureRect = { x = 126, y = 126, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "Head-Back.png",
				spriteColorRect = { x = 5, y = 6, width = 30, height = 26 }, 
				textureRect = { x = 168, y = 126, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "Head-Front.png",
				spriteColorRect = { x = 5, y = 6, width = 30, height = 26 }, 
				textureRect = { x = 210, y = 126, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "Head-Right.png",
				spriteColorRect = { x = 5, y = 6, width = 28, height = 26 }, 
				textureRect = { x = 252, y = 126, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "HumanNose-Right.png",
				spriteColorRect = { x = 28, y = 25, width = 4, height = 4 }, 
				textureRect = { x = 294, y = 126, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "Legs-Back1.png",
				spriteColorRect = { x = 11, y = 35, width = 18, height = 4 }, 
				textureRect = { x = 336, y = 126, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "Legs-Back2.png",
				spriteColorRect = { x = 11, y = 35, width = 18, height = 2 }, 
				textureRect = { x = 378, y = 126, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "Legs-Back3.png",
				spriteColorRect = { x = 11, y = 35, width = 18, height = 4 }, 
				textureRect = { x = 420, y = 126, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "Legs-Front1.png",
				spriteColorRect = { x = 11, y = 34, width = 18, height = 6 }, 
				textureRect = { x = 462, y = 126, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "Legs-Front2.png",
				spriteColorRect = { x = 11, y = 35, width = 18, height = 2 }, 
				textureRect = { x = 0, y = 168, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "Legs-Front3.png",
				spriteColorRect = { x = 11, y = 35, width = 18, height = 4 }, 
				textureRect = { x = 42, y = 168, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "Legs-Right1.png",
				spriteColorRect = { x = 12, y = 35, width = 14, height = 2 }, 
				textureRect = { x = 84, y = 168, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "Legs-Right2.png",
				spriteColorRect = { x = 12, y = 35, width = 14, height = 2 }, 
				textureRect = { x = 126, y = 168, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "Legs-Right3.png",
				spriteColorRect = { x = 12, y = 35, width = 14, height = 2 }, 
				textureRect = { x = 168, y = 168, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "LipStick-Front.png",
				spriteColorRect = { x = 18, y = 27, width = 4, height = 2 }, 
				textureRect = { x = 210, y = 168, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "LipStick-Right.png",
				spriteColorRect = { x = 25, y = 26, width = 2, height = 2 }, 
				textureRect = { x = 252, y = 168, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "LongWavy-Back.png",
				spriteColorRect = { x = 5, y = 6, width = 30, height = 30 }, 
				textureRect = { x = 294, y = 168, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "LongWavy-Front.png",
				spriteColorRect = { x = 5, y = 6, width = 30, height = 30 }, 
				textureRect = { x = 336, y = 168, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "LongWavy-Right.png",
				spriteColorRect = { x = 5, y = 5, width = 28, height = 30 }, 
				textureRect = { x = 378, y = 168, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "MaleBody-Back.png",
				spriteColorRect = { x = 9, y = 27, width = 22, height = 8 }, 
				textureRect = { x = 420, y = 168, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "MaleBody-Front.png",
				spriteColorRect = { x = 9, y = 27, width = 22, height = 8 }, 
				textureRect = { x = 462, y = 168, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "MaleBody-Right.png",
				spriteColorRect = { x = 11, y = 30, width = 16, height = 8 }, 
				textureRect = { x = 0, y = 210, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "OuterEye-Front.png",
				spriteColorRect = { x = 14, y = 23, width = 12, height = 4 }, 
				textureRect = { x = 42, y = 210, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "OuterEye-Right.png",
				spriteColorRect = { x = 25, y = 20, width = 4, height = 6 }, 
				textureRect = { x = 84, y = 210, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "PonyTail-Back.png",
				spriteColorRect = { x = 6, y = 6, width = 28, height = 28 }, 
				textureRect = { x = 126, y = 210, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "PonyTail-Front.png",
				spriteColorRect = { x = 3, y = 6, width = 32, height = 16 }, 
				textureRect = { x = 168, y = 210, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "PonyTail-Right.png",
				spriteColorRect = { x = 1, y = 6, width = 32, height = 28 }, 
				textureRect = { x = 210, y = 210, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "Regular-Back.png",
				spriteColorRect = { x = 6, y = 6, width = 28, height = 26 }, 
				textureRect = { x = 252, y = 210, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "Regular-Front.png",
				spriteColorRect = { x = 6, y = 5, width = 28, height = 20 }, 
				textureRect = { x = 294, y = 210, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "Regular-Right.png",
				spriteColorRect = { x = 5, y = 5, width = 28, height = 24 }, 
				textureRect = { x = 336, y = 210, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "Spiked-Back.png",
				spriteColorRect = { x = 4, y = 4, width = 32, height = 26 }, 
				textureRect = { x = 378, y = 210, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "Spiked-Front.png",
				spriteColorRect = { x = 4, y = 4, width = 32, height = 20 }, 
				textureRect = { x = 420, y = 210, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "Spiked-Right.png",
				spriteColorRect = { x = 3, y = 4, width = 32, height = 26 }, 
				textureRect = { x = 462, y = 210, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "Straight-Back.png",
				spriteColorRect = { x = 6, y = 6, width = 28, height = 30 }, 
				textureRect = { x = 0, y = 252, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "Straight-Front.png",
				spriteColorRect = { x = 6, y = 6, width = 28, height = 24 }, 
				textureRect = { x = 42, y = 252, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "Straight-Right.png",
				spriteColorRect = { x = 5, y = 7, width = 28, height = 26 }, 
				textureRect = { x = 84, y = 252, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "TruckerHat-Back.png",
				spriteColorRect = { x = 5, y = 4, width = 28, height = 20 }, 
				textureRect = { x = 126, y = 252, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "TruckerHat-Front.png",
				spriteColorRect = { x = 6, y = 4, width = 28, height = 20 }, 
				textureRect = { x = 168, y = 252, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "TruckerHat-Right.png",
				spriteColorRect = { x = 5, y = 4, width = 30, height = 18 }, 
				textureRect = { x = 210, y = 252, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "ZombieArms-Back.png",
				spriteColorRect = { x = 10, y = 29, width = 20, height = 8 }, 
				textureRect = { x = 252, y = 252, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "ZombieArms-Front.png",
				spriteColorRect = { x = 5, y = 27, width = 30, height = 12 }, 
				textureRect = { x = 294, y = 252, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "ZombieArms-Right.png",
				spriteColorRect = { x = 3, y = 27, width = 30, height = 8 }, 
				textureRect = { x = 336, y = 252, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "ZombieEyes-Front.png",
				spriteColorRect = { x = 5, y = 13, width = 24, height = 14 }, 
				textureRect = { x = 378, y = 252, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "ZombieEyes-Right.png",
				spriteColorRect = { x = 23, y = 19, width = 6, height = 8 }, 
				textureRect = { x = 420, y = 252, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "ZombieNose-Front.png",
				spriteColorRect = { x = 18, y = 26, width = 4, height = 4 }, 
				textureRect = { x = 462, y = 252, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "ZombieNose-Right.png",
				spriteColorRect = { x = 28, y = 25, width = 2, height = 2 }, 
				textureRect = { x = 0, y = 294, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "zDreads-Back.png",
				spriteColorRect = { x = 4, y = 4, width = 32, height = 36 }, 
				textureRect = { x = 42, y = 294, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "zDreads-Front.png",
				spriteColorRect = { x = 4, y = 5, width = 32, height = 34 }, 
				textureRect = { x = 84, y = 294, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "zDreads-Right.png",
				spriteColorRect = { x = 4, y = 6, width = 30, height = 28 }, 
				textureRect = { x = 126, y = 294, width = 40, height = 40 }, 
				spriteSourceSize = { width = 40, height = 40 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
		}
	}

	return sheet
end